version: '3.0'
services:

  mysql-server:
    container_name:  mysql-server
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data-mysql:/var/lib/mysql
    networks:
      - isep_academy
    ports:
      - "3306:3306"
    logging:
      options:
        max-size: 50m

  phpmyadmin:
    depends_on:
      - mysql-server
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - isep_academy
    ports:
      - "8080:80"
    logging:
      options:
        max-size: 50m

  academy:
    depends_on:
      - mysql-server
    container_name: academy
    build: .
    restart: unless-stopped
    networks:
      - isep_academy
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    logging:
      options:
        max-size: 50m

volumes:
  app:
  data-mysql:

networks:
  isep_academy:
    ipam:
      driver: default
      config:
        - subnet: 172.200.1.0/24
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: isep_academy